Use flake8
hyperskill/hs-test-python pull request #33
Opened 2022-09-28 18:07 UTC by meanmail

Task: [#HSPC-](https://vyahhi.myjetbrains.com/youtrack/issue/HSPC-)

**Dependencies**
- !

**Reviewers**
- [ ] @

**Description**

2022-09-29 18:59 UTC, aaaaaa2493 requested changes

2022-09-29 18:59 UTC, aaaaaa2493 commented on tests/outcomes/separate_package/find_module_no_info_analyze_imports/dir/main.py
> -import main2
Same

2022-09-29 18:59 UTC, aaaaaa2493 commented on tests/outcomes/separate_package/find_module_no_info_analyze_imports/dir/main2.py
> -import main3, main4
Same

2022-09-29 18:59 UTC, aaaaaa2493 commented on tests/outcomes/separate_package/find_module_no_info_analyze_imports_2/dir/main2.py
> -import main3
Same

2022-09-29 18:59 UTC, aaaaaa2493 commented on tests/outcomes/separate_package/find_module_no_info_analyze_imports_3/dir/main2.py
> -import main3
Same

2022-09-29 18:59 UTC, aaaaaa2493 commented on tests/outcomes/separate_package/find_module_no_info_analyze_name_main/dir/main2.py
> -import main3
Same

2022-09-29 18:59 UTC, aaaaaa2493 commented on tests/outcomes/separate_package/find_module_no_info_analyze_name_main_2/dir/main2.py
> -import main3
Same

2022-09-29 18:59 UTC, aaaaaa2493 commented on tests/outcomes/separate_package/find_module_no_info_analyze_name_main_3/dir/main2.py
> -import main3
Same

2022-09-29 18:59 UTC, aaaaaa2493 commented on tests/outcomes/separate_package/find_module_no_info_analyze_name_main_4/dir/main2.py
> -import main3
Same

2022-09-29 18:59 UTC, aaaaaa2493 commented on tests/outcomes/separate_package/find_module_no_info_analyze_name_main_4/dir/main3.py
> -import main4
Same

2022-10-13 13:00 UTC, inuur approved these changes

2022-10-13 15:12 UTC, merged